[package]
name = "block-id"
version = "0.2.1"
edition = "2021"
readme = "README.md"
repository = "https://github.com/drifting-in-space/block-id"
license = "MIT OR Apache-2.0"
description = "Library for generating opaque, unique, and short string values from (unsigned) integers"

[dependencies]
rand = "0.9.2"
rand_core = "0.9.3"
rand_pcg = "0.9.0"
